from analytics.sales_analytics import SalesAnalytics
from analytics.customer_analytics import CustomerAnalytics
from analytics.campaign_analytics import CampaignAnalytics
from analytics.funnel_analytics import FunnelAnalytics
